### PR TITLE
Fix #29 with the same trick as pathsx (dmd 2.067.0)

### LINKED ISSUE #29: Error when trying to build with dmd 2.067
$ make
dmd -c -O -inline -release -ofwarp.o cmdline.d constexpr.d context.d directive.d expanded.d file.d id.d lexer.d loc.d macros.d main.d number.d outdeps.d ranges.d skip.d sources.d stringlit.d textbuf.d charclass.d
context.d(87): Error: function cmdline.combineSearchPaths (const(string[]) includePaths, const(string[]) sysIncludePaths, out string[] paths, out ulong sysIndex) is not callable using argument types (const(string[]), const(string[]), string[], const(ulong))
main.d(41): Error: template instance context.Context!(LockingTextWriter) error instantiating
make: *** [warp.o] Error 1

### PR DESCRIPTION
**Pull request by Eyyub**

### CODE REVIEW

**Comment by markisaa** [comment]
Just pushed this through. Also, please accept my apologies, I seem to have misapplied our convoluted scripts and it believes I am the author of the content. That was not my intent.

**Comment by Eyyub** [comment]
You're welcome !
