### ISSUE TITLE
Fail to compile on dmd/gdc

### ISSUE THREAD

**Issue by zhanxw** [facebook/warp#30]
Failed to compile on dmd (dmd_2.066.1-0_amd64.deb) and gdc (gdc (Ubuntu 4.9.1-16ubuntu6) 4.9.1).
Each produced more than two thousand lines of error messages.

dmd errors:
>DC=dmd make
dmd -c -O -inline -release -ofwarp.o cmdline.d constexpr.d context.d directive.d expanded.d file.d id.d lexer.d loc.d macros.d main.d number.d outdeps.d ranges.d skip.d sources.d stringlit.d textbuf.d charclass.d
gcc -m64 -Bthird-party2/binutils/2.21.1/centos6-native/da39a3e/bin/gold -Bthird-party2/glibc/2.17/gcc-4.8.1-glibc-2.17-fb/99df8fc/lib -L/home/aalexandre/bin/../d/phobos/generated/linux/release/default -l:libphobos2.a -lpthread -lm -lrt -o warp warp.o
warp.o:(.data+0x658): undefined reference to `_D9Exception7__ClassZ'
warp.o:(.data+0x678): undefined reference to `_D6object9Throwable7__ClassZ'
warp.o:(.data+0x6d8): undefined reference to `_D6object9Throwable7__ClassZ'
warp.o:(.rodata+0x828): undefined reference to `_D3std5stdio12__ModuleInfoZ'
warp.o:(.rodata+0x830): undefined reference to `_D3std5range12__ModuleInfoZ'
warp.o:(.rodata+0x838): undefined reference to `_D3std4path12__ModuleInfoZ'
warp.o:(.rodata+0x840): undefined reference to `_D3std5array12__ModuleInfoZ'
warp.o:(.rodata+0x848): undefined reference to `_D3std9algorithm12__ModuleInfoZ'

gdc errors:

>DC=gdc make
gdc -c -O4 -frelease -fno-bounds-check -fbuiltin -owarp.o cmdline.d constexpr.d context.d directive.d expanded.d file.d id.d lexer.d loc.d macros.d main.d number.d outdeps.d ranges.d skip.d sources.d stringlit.d textbuf.d charclass.d
gcc -m64 -Bthird-party2/binutils/2.21.1/centos6-native/da39a3e/bin/gold -Bthird-party2/glibc/2.17/gcc-4.8.1-glibc-2.17-fb/99df8fc/lib -L/home/aalexandre/bin/../d/phobos/generated/linux/release/default -l:libphobos2.a -lpthread -lm -lrt -o warp warp.o
warp.o: In function `_D3std6getopt24__T12handleOptionTPAAyaZ12handleOptionFAyaPAAyaKAAyaKS3std6getopt13configurationbZv12__dgliteral7MFNaNbNfZAxa':
cmdline.d:(.text+0x208): undefined reference to `_D11TypeInfo_Aa6__initZ'
cmdline.d:(.text+0x20f): undefined reference to `_d_arraycatnT'
warp.o: In function `_D3std6getopt23__T12handleOptionTPAyaZ12handleOptionFAyaPAyaKAAyaKS3std6getopt13configurationbZv12__dgliteral7MFNaNbNfZAxa':
cmdline.d:(.text+0x248): undefined reference to `_D11TypeInfo_Aa6__initZ'
cmdline.d:(.text+0x24f): undefined reference to `_d_arraycatnT'
warp.o: In function `_D3std4conv17__T6toImplTAyaTmZ6toImplFNaNemkE3std5ascii10LetterCaseZAya30__T20toStringRadixConvertVm48Z20toStringRadixConvertMFkZAya':
cmdline.d:(.text+0x2bf): undefined reference to `_D11TypeInfo_Aa6__initZ'
....

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
