### ISSUE TITLE
Error when trying to build with dmd 2.067

### ISSUE THREAD

**Issue by tfarina** [facebook/warp#29]
$ make
dmd -c -O -inline -release -ofwarp.o cmdline.d constexpr.d context.d directive.d expanded.d file.d id.d lexer.d loc.d macros.d main.d number.d outdeps.d ranges.d skip.d sources.d stringlit.d textbuf.d charclass.d
context.d(87): Error: function cmdline.combineSearchPaths (const(string[]) includePaths, const(string[]) sysIncludePaths, out string[] paths, out ulong sysIndex) is not callable using argument types (const(string[]), const(string[]), string[], const(ulong))
main.d(41): Error: template instance context.Context!(LockingTextWriter) error instantiating
make: *** [warp.o] Error 1

**Comment by tfarina** [comment]
$ dmd --version
DMD64 D Compiler v2.067-devel-0a80299
Copyright (c) 1999-2014 by Digital Mars written by Walter Bright
